services:

  app:
    image: l4rm4nd/vouchervault:1.4.x
    container_name: vouchervault
    restart: unless-stopped
    environment:
      # your FQDN or IP; used to define ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS
      - DOMAIN=vouchervault.example.com 
      # set to True if you use a reverse proxy with tls; enables secure cookie flag and hsts
      - SECURE_COOKIES=False
      # send notifications xx days prior expiry
      - EXPIRY_THRESHOLD_DAYS=90
      # ------- USE PSQL DB --------
      - DB_ENGINE=postgres
      - POSTGRES_USER=vouchervault
      - POSTGRES_PASSWORD=vouchervault
      - POSTGRES_DB=vouchervault
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./volume-data/database:/opt/app/database

  redis:
    image: redis:7.2-alpine
    container_name: vouchervault-redis
    restart: unless-stopped
    expose:
      - 6379

  db:
    image: postgres:16-alpine
    container_name: vouchervault-psql
    restart: unless-stopped
    expose:
      - 5432
    volumes:
      - ./volume-data/database/psql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vouchervault
      - POSTGRES_PASSWORD=vouchervault
      - POSTGRES_DB=vouchervault